version: "3.8"
services:
  deployment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true